---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: ReconfigVM_Task_memoryHotAddEnabled
    inherits: 
    description: 
  fields:
  - method1:
      value: ReconfigVM_Task_memoryHotAddEnabled
