---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Provision VM from Template
    name: template
    inherits: 
    description: 
  fields:
  - AcquireMACAddress:
      value: ! '#/Infrastructure/VM/Provisioning/StateMachines/Methods/GenerateMACAddress#${/#miq_provision.source.vendor}'
  - PreProvision:
      value: /Integration/VMware/RBVMOMI/create_folder
  - Provision:
      value: /Infrastructure/VM/Provisioning/StateMachines/Methods/Provision
  - CheckProvisioned:
      value: /Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned
  - AddVMToService:
      value: /Infrastructure/VM/Provisioning/StateMachines/Methods/AddVMToService
