---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Default
    name: Default
    inherits: 
    description: 
  fields:
  - max_cpus:
      value: '1'
  - max_memory:
      value: '1024'
